name: finance-analysis
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - flask=2.0.1
  - pandas=1.3.3
  - numpy=1.21.2
  - scipy=1.7.1
  - matplotlib=3.4.3
  - requests=2.26.0
  - pip=21.2.4
  - pip:
    - yfinance==0.1.63
    - alpha_vantage==2.3.1
    - plotly==5.3.1
    - beautifulsoup4==4.10.0
    - lxml==4.6.3
    - nltk==3.6.3
    - textblob==0.15.3
    - python-dotenv==0.19.0
    - schedule==1.1.0
    - gunicorn==20.1.0
