name: finance-analysis
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - flask
    - pandas
    - numpy
    - scipy
    - matplotlib
    - requests
    - yfinance
    - alpha_vantage
    - plotly
    - beautifulsoup4
    - lxml
    - nltk
    - textblob
    - python-dotenv
    - schedule
    - gunicorn
    - selenium
    - webdriver-manager
    - werkzeug
    - together