name: Update Financial Data and Deploy

on:
  schedule:
    - cron: '0 5 * * *'  # Daily at 9 PM PST (5 AM UTC)
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set up environment variables
      run: |
        echo "TOKEN_GIST=${{ secrets.TOKEN_GIST }}" >> $GITHUB_ENV
    
    - name: Generate static site from cloud data
      run: |
        python generate_static.py
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        publish_branch: gh-pages
        force_orphan: true